project:
  type: book
  output-dir: docs

book:
  title: "Python Essentials for Wrestling with Data"
  author: "Tero Jalkanen"
  date: today
  repo-url: https://github.com/TeroJii/python-book/
  repo-actions: [issue]
  chapters:
    - index.qmd
    - part: "The Very Basics"
      chapters:
        - intro.qmd
        - control_flow.qmd
        - functions.qmd
    - part: "Basic Data Manipulation"
      chapters:
        - numpy.qmd
        - pandas.qmd
        - pandas_advanced.qmd
    - part: "Data Visualization"
      chapters:
        - matplotlib.qmd
        - seaborn.qmd
    - part: "Modelling"
      chapters:
        - linear_regression.qmd
        - logistic_regression.qmd
    - part: "Wrapping up"
      chapters:
        - summary.qmd
        - references.qmd
  appendices:
    - installation.qmd
    - environment.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt



