project:
  type: book
  output-dir: docs

book:
  title: "Python Bytes: A Poor Man's Guide to Wrestling with Data"
  author: "Tero Jalkanen"
  date: today
  repo-url: https://github.com/TeroJii/python-book/
  repo-actions: [issue]
  chapters:
    - index.qmd
    - part: "The Very Basics"
    - intro.qmd
    - control_flow.qmd
    - functions.qmd
    - part: "Basic Data Manipulation"
      chapters:
        - pandas.qmd
    - part: "Modelling"
      chapters:
        - linear_regression.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt



