---
jupyter: python3
---

# Preface {.unnumbered}

```{python}
print('Hello World!')
```

Sometimes wrestling with data can really bite. However, it doesn't need to be that way. Python is a powerful tool for data analysis and visualisation, and it can help extract insight from your data and communicate them to the world. This book is meant to give you an overview of the core concepts in Python that are useful for data analysis. The approach aims to be pragmatic and hands-on, with concrete examples to help you get started. This should give you a solid foundation to build upon as you advance on your Python journey. It will help if you have some basic programming experience. Luckily, there are plenty of resources available online to help you if you get stuck. Just remember that programming is a skill that you need to keep practicing to get better at it.

So, who am I? My name is Tero and I work as a data science consultant. Previously, I have worked as a researcher in the pharmaceutical industry and academia. Over the years I have used several tools for analysing data. With the rise of data science and deep learning in particular, Python has become the most used programming language in the world. These days, you don't really need to look for reasons to learn Python. I started to write this book for myself, to have a reference to some core concepts in Python. If someone else finds it useful, that's great!

::: {.callout-note}
Please note that this book is currently work in progress. That being said, some chapters should already serve as decent references and/or introductions to certain topics. My hope and aim is that this book will serve as a useful reference to many core concepts in using Python for analyzing data.

Should you find the current state of this book too unpolished, take comfort in the fact that many excellent books on Python programming have been written. For example, Wes McKinney's Python for data analysis will give an in-depth view on many Python concepts (@McKinneyBook).
::: 

::: {.content-visible when-format="html"}

::: {.callout-tip}
## About the Online Version

You are currently reading the free online version of this book. You can find the source code for this book on GitHub. If you find this book useful, please consider supporting the author by purchasing a copy on **TO BE ANNOUNCED**. Thank you!

:::

:::
