---
jupyter: python3
---

# NumPy

So far we have only used commands that come with the standard Python distribution. However, Python is a very popular language for scientific computing and there are many packages that can be used to extend its capabilities. One of the most fundamental packages for extending Pythons capabilities in this domain is NumPy. NumPy is also the cornerstone for many packages which are important for doing data analysis with Python, including but not limited to Pandas, SciPy, and Matplotlib.

## Installation and Loading

You can install Python packages using the `pip` command. Another popular package manager is `conda`. Either of these package managers will do the trick.

:::{.callout-tip}
Installing NumPy using pip in rather simple. Just run the following command in your terminal or command prompt:

```bash
pip install numpy
```	
:::

Once you have installed the NumPy package, you can load it using the following command.

```{python}
#| code-fold: false
import numpy as np
```

We have imported the NumPy package and aliased it as `np`. This is a common convention when working with NumPy. We can now use the functions and classes provided by NumPy by prefixing them with `np.`. For example, generating a random number using NumPy would look like this:

```{python}
#| code-fold: false
np.random.rand(5)
```

## What can NumPy do?

One of the key concepts in NumPy are array and matrix data structures. Moreover, Numpy provides tools for working with these structures. The array is in principle quite similar to a list in Python, with a few key differences:

* Arrays can be multidimensional
* Arrays can only contain elements of the same type, whereas lists can contain elements of different types
* Arrays are optimized for numerical operations, whereas lists are not. This makes arrays much faster for numerical operations than lists, and also more memory efficient.

## NumPy Arrays

You can create a 1-D NumPy array from a list using the `np.array()` function. For example:

```{python}
#| code-fold: false
a = np.array([1, 2, 3, 4, 5])
a
```

You might have noticed that we actually used a list to create the NumPy array. We can naturally create a NumPy array from a list which has been assigned to a variable. For example, below we will cast a list to an array using the variable `my_list`:

```{python}
#| code-fold: false

my_list = [0, 1, 2, 3, 4, 5]
a = np.array(my_list)
print(a)
```

Now accessing the elements of the array is similar to accessing the elements of a list. For example, to access the first element of the array, you can use the following code:

```{python}
#| code-fold: false
a[0]
```

This works just like it would for a list:

```{python}
#| code-fold: false
my_list[0]
```

You can also use the slice notation to access a range of elements in the array. For example, the following code will access the elements from the second to the fourth element of the array. So in other words from index one to index three (it can be confusing I know).

```{python}
#| code-fold: false
a[1:4]
```

With arrays you can also do something called broadcasting. This means that you can apply an operation to every element in the array. For example, the following code will multiply every element in the array by 2.

```{python}
#| code-fold: false
a * 2
```

This is not possible with lists as you will see by looking at the example below.

```{python}
#| code-fold: false
my_list * 2
```

You can also apply mathematical functions to the array. For example, the following code will calculate the square of first three elements in the array.

```{python}
#| code-fold: false

square_first_three = np.square(a[:3])
print(square_first_three)
```

You should be aware that the array is not changed by these operations, as we can see by printing the array.

```{python}	
#| code-fold: false
a
```


:::{.callout-warning}
However, when you broadcast on a slice of an array, the original array is changed. For example, the following code will change the first three elements of the array to their squares.

```{python}
#| code-fold: false
squared_slice = a[:3]
squared_slice **= 2

print(squared_slice)
print(a)
```

:::

You can use the `copy()` method to create a copy of the array. This way you can change the copy without changing the original array. For example, the following code will create a copy of the array and change the copy without changing the original array.

```{python}
#| code-fold: false

a_copy = a.copy()
a_copy[0] = 100
print(a_copy)
print(a)
```

### Other Ways to Create 1-D Arrays

`np.array()` is not the only way to create a NumPy array.
We can also create a one dimensional NumPy array for a range of numbers conveniently using the `np.arange()` function.

```{python}
#| code-fold: false
a = np.arange(1, 6)
print(a)
```

You can also determine a step size for the range of numbers. For example, the following code will create an array with numbers from 0 to 10 with a step size of 2.

```{python}
#| code-fold: false
a_steps = np.arange(0, 11, 2)
print(a_steps)
```


### 2-D Matrices

You can create a 2-D NumPy array from a list of lists by using the `np.array()` function.

```{python}
#| code-fold: false
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b
```

You can access elements of a 2-D array using two indices. For example, the following code will access the element in the second row and third column of the array.

```{python}
#| code-fold: false
# index for the second row and third column
b[1, 2]
```

There is also a double bracket notation for accessing elements in a 2-D array. For example, the following code will access the element in the second row and third column of the array.

```{python}
#| code-fold: false
b[1][2]
```

Either of the two methods will work, but the first method should be more efficient.

## Some convenient functions

Here are some convenient functions that you can use to create NumPy arrays:

* `np.zeros()`: Creates an array of zeros
* `np.ones()`: Creates an array of ones
* `np.linspace()`: Creates an array of evenly spaced numbers over a specified range
* `np.eye()`: Creates an identity matrix

Let's see some examples.

### Zeros and Ones

You can create an array of zeros using the `np.zeros()` function. For example, the following code will create an array of zeros with 5 elements.

```{python}
#| code-fold: false
np.zeros(5)
```

For a 2-D array, you can specify the shape of the array as a tuple. For example, the following code will create a 2-D array of zeros with 3 rows and 4 columns.

```{python}
#| code-fold: false
np.zeros((3, 4))
```

Using ones is similar to using zeros. Let's create a 5 by 6 matrix of ones.

```{python}
#| code-fold: false
np.ones((5, 6))
```


### Linspace

The `np.linspace()` function is used to create an array of evenly spaced numbers over a specified range. For example, the following code will create an array of 10 numbers between 0 and 5.

```{python}
#| code-fold: false
np.linspace(0, 5, 10)
```

How does it differ from `np.arange()` you might ask? The `np.linspace()` function will always include the start and end values, whereas the `np.arange()` function will not include the end value.

### Eye

This function is used for creating an identity matrix. An identity matrix is a square matrix with ones on the diagonal and zeros elsewhere. We can create a 4 by 4 identity matrix with the following code.

```{python}
#| code-fold: false
np.eye(4)
```

The identity matrix has many important uses in linear algebra and other areas of mathematics.


## NumPy for Random Number Generation

Random numbers are needed for a variety of purposes in data analysis and machine learning. NumPy provides a number of functions for generating random numbers. Here are some of the most commonly used functions:

* `np.random.rand()`: Generates random numbers from a uniform distribution
* `np.random.randn()`: Generates random numbers from a standard normal distribution
* `np.random.randint()`: Generates random integers

These functions allow us to create NumPy arrays with random numbers taken from different distributions. 

### Uniform Distribution

The uniform distribution refers generally to random numbers between 0 and 1. The `np.random.rand()` function generates random numbers from a uniform distribution. For example, the following code will generate an array of 5 random numbers between 0 and 1.

```{python}
#| code-fold: false

np.random.rand(5)
```

You can also generate a 2-D array of random numbers. For example, the following code will generate a 3 by 4 array of random numbers.

```{python}
#| code-fold: false
arr = np.random.rand(3, 4)
arr
```

We can always check the shape of the array using the `shape` attribute.

```{python}
#| code-fold: false
arr.shape
```

The `shape` attribute returns a tuple with the dimensions of the array. In this case, the array has 3 rows and 4 columns. The function `reshape()` allows us to change the shape of the array. For example, we can reshape the array to have 4 rows and 3 columns, or to be one dimensional.

```{python}	
#| code-fold: false

arr.reshape(4, 3)
```

```{python}
#| code-fold: false

arr.reshape(12)
```

You might have noticed, but the two dimensional array has two square brackets on the outer edges, whereas the one dimensional array has only one square bracket per side.

Finally, we can also check the data type of the array using the `dtype` attribute. In case we want to change the data type of the array, we can use the `astype()` method.

```{python}
#| code-fold: false

arr.dtype
```

```{python}
#| code-fold: false

arr.astype(int)
```

### Normal Distribution

The normal distribution is quite possibly the most important distribution in statistics. The `np.random.randn()` function generates random numbers from a standard normal distribution. If we want to save ourselves some typing we can import the function directly.

```{python}
#| code-fold: false
from numpy.random import randn
```

This allows us to use the function without the `np.` prefix. Like this:

```{python}
#| code-fold: false
# create 5 random numbers from a standard normal distribution
randn(5)
```

The standard normal distribution is centered around zero and has a standard deviation of one. So, if we want to change the mean and standard deviation of our normal distribution, we can multiply the random numbers by the standard deviation and shift the mean by addition. For example, the following code will generate 5 random numbers from a normal distribution with a mean of 10 and a standard deviation of 2.

```{python}
#| code-fold: false
# multiply by sd and add mean
randn(5) * 2 + 10
```

### Random Integers

The `np.random.randint()` function generates random integers. For example, the following code will generate eight random integers between 0 and 10.

```{python}
#| code-fold: false
from numpy.random import randint

randint(0, 10, 8)
```

If you want the results to be reproducible, you can set the seed using the `np.random.seed()` function. For example, the following code will generate the same random numbers every time you run it.

```{python}
#| code-fold: false
np.random.seed(42)
randint(0, 10, 8)
```

The this code draws numbers with replacement from the integers between 0 and 10. If you want to draw numbers without replacement, you can use the `choice()` function. For example, the following code will draw 5 random numbers without replacement from the integers between 0 and 10.

```{python}
#| code-fold: false

np.random.choice(10, 5, replace=False)
```

## Array Operations

You can perform element-wise operations on NumPy arrays. For example, you can add two arrays together, subtract one array from another, multiply two arrays, and divide one array by another. Let's see some examples.

### Basic Operations

You can perform basic arithmetic operations on NumPy arrays. For example, the following code will add two arrays together.

```{python}
#| code-fold: false
a = np.array([1, 2, 3, 4, 5])

a + a
```

The same goes for subtraction and multiplication.

```{python}
#| code-fold: false
# subtraction
a - a
```

```{python}
#| code-fold: false
# multiplication
a * a
```

You can also divide two arrays:

```{python}
#| code-fold: false

a / a
```

Scalar operations are also possible. For example, the following code will multiply every element in the array by 2.

```{python}
#| code-fold: false
a * 2
```

You can also add or subtract a scalar from an array.

```{python}
#| code-fold: false
# addition
a + 2
```


### Universal Functions

NumPy provides a number of universal functions that can be applied to arrays. For example, the `np.sqrt()` function calculates the square root of every element in the array.

```{python}
#| code-fold: false
np.sqrt(a)
```

You can do things like finding the maximum or minimum value in an array.

```{python}
#| code-fold: false
# maximum value
np.max(a)
```

This is equivalent to using the `max()` method.

```{python}
#| code-fold: false
a.max()
```

You can also find the index of the maximum value in the array.

```{python}
#| code-fold: false
np.argmax(a)
```

Trigonometric functions are also available, such as `np.sin()`, `np.cos()`, and `np.tan()`.

```{python}
#| code-fold: false
np.cos(a)
```

